///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/musicamenu.aks
/// Generation time: mar 02 nov 2021 18:37:29 CET
///

/// Song 'song_menu1' metadata macros
#define song_menu1_address  0x0040
#define song_menu1_size     176
#define song_menu1_end      0xef

/// Song 'song_menu1' array declaration
extern void song_menu1[song_menu1_size];
