// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _g_palette_bonus_H_
#define _g_palette_bonus_H_

#include <types.h>

extern const u8 g_palette_bonus[16];

#endif
